name-template: "$NEXT_PATCH_VERSION 🌈"
tag-template: "$NEXT_PATCH_VERSION"
categories:
  - title: "🚀 Features"
    label: "feature"
  - title: "🐛 Bug Fixes"
    label: "fix"
  - title: "🧰 Maintenance"
    label: "chore"
  - title: "⚙️ Dependencies"
    label: "dependencies"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## Changes

  $CHANGES
