name-template: "$NEXT_PATCH_VERSION 🌈"
tag-template: "$NEXT_PATCH_VERSION"
categories:
  - title: "🚀 Features"
    label: "feature"
  - title: "🐛 Bug Fixes"
    label: "bug"
  - title: "🧯 Hotfixes"
    label: "hotfix"
  - title: "⚙️ Dependencies maintenance"
    label: "dependencies"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## Changes

  $CHANGES
