kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: install_deps
    image: node:8.15.0
    volumes:
      - name: cache
        path: /tmp/cache
    commands:
      - node -v
      - npm -v
      - yarn -v
      - yarn install --pure-lockfile --cache-folder /tmp/cache/yarn
    when:
      branch:
        - master
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/**']

  - name: api_test
    image: node:8.15.0
    commands:
      - yarn test:api
    when:
      branch:
        - master
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/api/**']

  - name: scheduler_test
    image: node:8.15.0
    commands:
      - yarn test:scheduler
    when:
      branch:
        - master
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/scheduler/**']

  - name: app_test
    image: node:8.15.0
    commands:
      - yarn test:app
    when:
      branch:
        - master
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/app/**']

  - name: app_lint
    image: node:8.15.0
    commands:
      - yarn lint:app
    when:
      branch:
        - master
      changeset:
        includes:
          ['.eslintignore', '.prettierignore', '.prettierrc', 'packages/app/**']
  - name: analytics_lint
    image: node:8.15.0
    commands:
      - yarn lint:analytics
    when:
      branch:
        - master
      changeset:
        includes:
          [
            '.eslintignore',
            '.prettierignore',
            '.prettierrc',
            'packages/analytics/**',
          ]
  - name: api_lint
    image: node:8.15.0
    commands:
      - yarn lint:api
    when:
      branch:
        - master
      changeset:
        includes:
          ['.eslintignore', '.prettierignore', '.prettierrc', 'packages/api/**']
  - name: scheduler_lint
    image: node:8.15.0
    commands:
      - yarn lint:scheduler
    when:
      branch:
        - master
      changeset:
        includes:
          [
            '.eslintignore',
            '.prettierignore',
            '.prettierrc',
            'packages/scheduler/**',
          ]

  - name: web_build
    image: node:8.15.0
    commands:
      - yarn build:web
    when:
      branch:
        - master
      event: push
      status: success
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/web/**']
  - name: app_build
    image: node:8.15.0
    commands:
      - yarn build:app
    when:
      branch:
        - master

      event: push
      status: success
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/app/**']

  - name: web_publish
    image: lucap/drone-netlify
    settings:
      token:
        from_secret: netlify_account_token
      site_id: 3ee97675-c7e2-47cc-8a8c-b6b24ca3fbf9
      site_name: web-amgaventures
      #domain: web.amgaventures.com
      path: packages/web/build
    when:
      branch:
        - master
      event: push
      status: success
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/web/**']
  - name: app_publish
    image: lucap/drone-netlify
    settings:
      token:
        from_secret: netlify_account_token
      site_id: 7d8053d6-80e8-4751-9a57-f5b6e8f8c271
      site_name: app-amgaventures
      #domain: app.amgaventures.com
      path: packages/app/build
    when:
      branch:
        - master
      event: push
      status: success
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/app/**']
  - name: analytics_publish
    image: node:8.15.0
    environment:
      DOKKU_SSH_KEY:
        from_secret: DOKKU_SSH_KEY
    commands:
      - mkdir /root/.ssh
      - echo -n "$DOKKU_SSH_KEY" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa

      - touch /root/.ssh/known_hosts
      - chmod 600 /root/.ssh/known_hosts
      - ssh-keyscan -t rsa dokku.amgaventures.com > /etc/ssh/ssh_known_hosts 2> /dev/null

      - git remote add analytics dokku@dokku.amgaventures.com:analytics
      - git push analytics
    when:
      branch: master
      event: push
      status: success
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/analytics/**']
  - name: api_publish
    image: node:8.15.0
    environment:
      DOKKU_SSH_KEY:
        from_secret: DOKKU_SSH_KEY
    commands:
      - mkdir /root/.ssh
      - echo -n "$DOKKU_SSH_KEY" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa

      - touch /root/.ssh/known_hosts
      - chmod 600 /root/.ssh/known_hosts
      - ssh-keyscan -t rsa dokku.amgaventures.com > /etc/ssh/ssh_known_hosts 2> /dev/null

      - git remote add api dokku@dokku.amgaventures.com:api
      - git push api
    when:
      branch: master
      event: push
      status: success
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/api/**']

  - name: scheduler_publish
    image: node:8.15.0
    environment:
      DOKKU_SSH_KEY:
        from_secret: DOKKU_SSH_KEY
    commands:
      - mkdir /root/.ssh
      - echo -n "$DOKKU_SSH_KEY" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa

      - touch /root/.ssh/known_hosts
      - chmod 600 /root/.ssh/known_hosts
      - ssh-keyscan -t rsa dokku.amgaventures.com > /etc/ssh/ssh_known_hosts 2> /dev/null

      - git remote add scheduler dokku@dokku.amgaventures.com:scheduler
      - git push scheduler
    when:
      branch: master
      event: push
      status: success
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/scheduler/**']

  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: dev
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded ({{build.link}}). Good job. <@{{build.author}}>
      {{else}}
        build {{build.number}} failed ({{build.link}}). Fix me please. <@channel>
      {{/success}}
    when:
      branch: master
      event: push
      status:
        - success
        - failure

volumes:
  - name: cache
    host:
      path: /var/lib/cache
