kind: pipeline
name: Default

platform:
  os: linux
  arch: amd64

steps:
  - name: install_deps
    image: node:8.15.0
    commands:
      - node -v
      - npm -v
      - yarn -v
      - yarn install --pure-lockfile
    when:
      branch:
        - master
        - features/*
        - patch/*
        - dependabot/*

  - name: app_test
    image: node:8.15.0
    commands:
      - yarn test:app

  - name: website_build
    image: node:8.15.0
    commands:
      - yarn build:website:stage
    when:
      branch:
        - master
        - features/*
        - patch/*
        - dependabot/*
      event: push
      status: success
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/website/**']

  - name: app_build
    image: node:8.15.0
    commands:
      - yarn build:app:stage
    when:
      branch:
        - master
        - features/*
        - patch/*
        - dependabot/*
      event: push
      status: success
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/app/**']

  - name: website_publish
    image: lucap/drone-netlify
    settings:
      token:
        from_secret: netlify_account_token
      site_id: 3ee97675-c7e2-47cc-8a8c-b6b24ca3fbf9
      site_name: web-amgaventures
      path: packages/website/build
    when:
      branch:
        - master
        - features/*
        - patch/*
        - dependabot/*
      event: push
      status: success
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/website/**']
  - name: app_publish
    image: lucap/drone-netlify
    settings:
      token:
        from_secret: netlify_account_token
      site_id: 7d8053d6-80e8-4751-9a57-f5b6e8f8c271
      site_name: app-amgaventures
      path: packages/app/build
    when:
      branch:
        - master
        - features/*
        - patch/*
        - dependabot/*
      event: push
      status: success
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/app/**']
  - name: analytics_publish
    image: node:8.15.0
    environment:
      SSH_KEY:
        from_secret: SSH_KEY
    commands:
      - mkdir /root/.ssh
      - echo -n "$SSH_KEY" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa

      - touch /root/.ssh/known_hosts
      - chmod 600 /root/.ssh/known_hosts
      - ssh-keyscan -t rsa dokku.amgaventures.com > /etc/ssh/ssh_known_hosts 2> /dev/null

      - git remote add analytics dokku@dokku.amgaventures.com:analytics
      - git push analytics
    when:
      branch: master
      event: push
      status: success
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/analytics/**']
  - name: api_publish
    image: node:8.15.0
    environment:
      SSH_KEY:
        from_secret: SSH_KEY
    commands:
      - mkdir /root/.ssh
      - echo -n "$SSH_KEY" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa

      - touch /root/.ssh/known_hosts
      - chmod 600 /root/.ssh/known_hosts
      - ssh-keyscan -t rsa dokku.amgaventures.com > /etc/ssh/ssh_known_hosts 2> /dev/null

      - git remote add api dokku@dokku.amgaventures.com:api
      - git push api
    when:
      branch: master
      event: push
      status: success
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/analytics/**']

  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: dev
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded ({{build.link}}). Good job. <@{{build.author}}>
      {{else}}
        build {{build.number}} failed ({{build.link}}). Fix me please. <@channel>
      {{/success}}
    when:
      branch: master
      event: push
      status:
        - success
        - failure
