kind: pipeline
name: Default

steps:
  - name: install_dependencies
    image: node:8.15.0
    volumes:
      - name: cache
        path: /tmp/cache
    commands:
      - node -v
      - npm -v
      - yarn -v
      - yarn install --pure-lockfile --cache-folder /tmp/cache/yarn

  - name: app_test
    image: node:8.15.0
    commands:
      - yarn test:app
    when:
      changeset:
        includes: ['packages/app/**']

  - name: app_build
    image: node:8.15.0
    commands:
      - yarn build:app
    when:
      changeset:
        includes: ['packages/app/**']

  - name: app_publish
    image: lucap/drone-netlify
    settings:
      token:
        from_secret: netlify_token
      site_id:
        from_secret: netlify_site_api_id
      path: packages/app/build
    when:
      branch:
        - master
      changeset:
        includes: ['packages/app/**']

  - name: notify_slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      template: '<{{build.link}}|Deployment #{{build.number}} ended> on <http://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.branch}}|{{repo.name}}:{{build.branch}}> by {{build.author}}'
    when:
      branch:
        - master
        - staging
      status:
        - success
        - failure

volumes:
  - name: cache
    host:
      path: /var/lib/cache
