kind: pipeline
name: Default

steps:
  - name: install_deps
    image: node:8.15.0
    commands:
      - node -v
      - npm -v
      - yarn -v
      - yarn install --pure-lockfile

  - name: analytics_publish
    image: node:8.15.0
    commands:
      - git --version
      - git push analytics
    when:
      branch: master
      event: push
      status: success
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/analytics/**']

  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: dev
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded ({{build.link}}). Good job. <@{{build.author}}>
      {{else}}
        build {{build.number}} failed ({{build.link}}). Fix me please. <@channel>
      {{/success}}
    when:
      branch: master
      event: push
      status:
        - success
        - failure
