kind: pipeline
name: Default

platform:
  os: linux
  arch: amd64

steps:
  - name: install_deps
    image: node:8.15.0
    commands:
      - node -v
      - npm -v
      - yarn -v
      - yarn install --pure-lockfile

  - name: analytics_publish
    image: node:8.15.0
    environment:
      SSH_KEY:
        from_secret: SSH_KEY
    commands:
      - mkdir /root/.ssh
      - echo -n "$SSH_KEY" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - cat /root/.ssh/id_rsa

      # add dokku.amgaventures.com to our known hosts.
      - touch /root/.ssh/known_hosts
      - chmod 600 /root/.ssh/known_hosts
      - ssh-keyscan -t rsa dokku.amgaventures.com > /etc/ssh/ssh_known_hosts 2> /dev/null

      - ssh -v dokku@dokku.amgaventures.com
      - git remote add analytics dokku@dokku.amgaventures.com:analytics
      - git push analytics
    when:
      branch: master
      event: push
      status: success
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/analytics/**']

  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: dev
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded ({{build.link}}). Good job. <@{{build.author}}>
      {{else}}
        build {{build.number}} failed ({{build.link}}). Fix me please. <@channel>
      {{/success}}
    when:
      branch: master
      event: push
      status:
        - success
        - failure
