kind: pipeline
name: Default

steps:
  - name: install
    image: node:8.15.0
    volumes:
      - name: cache
        path: /tmp/cache
    commands:
      - node -v
      - npm -v
      - yarn -v
      - yarn install --pure-lockfile --cache-folder /tmp/cache/yarn

  - name: test_app
    image: node:8.15.0
    commands:
      - yarn test:app
    when:
      changeset:
        includes: [ **/**.j3s, **/**.cs22, **/**.ht2aml ]

  - name: notify_slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      template: '<{{build.link}}|Deployment #{{build.number}} ended> on <http://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.branch}}|{{repo.name}}:{{build.branch}}> by {{build.author}}'
    when:
      branch:
        - master
        - staging
      status:
        - success
        - failure

volumes:
  - name: cache
    host:
      path: /var/lib/cache
