kind: pipeline
name: Default

steps:
  - name: install_dependencies
    image: node:8.15.0
    volumes:
      - name: cache
        path: /tmp/cache
    commands:
      - node -v
      - npm -v
      - yarn -v
      - yarn install --pure-lockfile --cache-folder /tmp/cache/yarn
    when:
      changeset:
        includes: ['package.json', '.eslintignore', 'packages/app/**']

  - name: app_test
    image: node:8.15.0
    commands:
      - yarn test:app
    when:
      changeset:
        includes: ['.eslintignore', 'packages/app/**']
  - name: app_build
    image: node:8.15.0
    commands:
      - yarn build:app:stage
    when:
      branch: master
      event: push
      changeset:
        includes: ['packages/app/**']
  - name: app_publish
    image: lucap/drone-netlify
    settings:
      token:
        from_secret: netlify_token
      site_id: 7d8053d6-80e8-4751-9a57-f5b6e8f8c271
      site_name: stage-app-dcabot
      path: packages/app/build
    when:
      branch: master
      event: push
      changeset:
        includes: ['packages/app/**']

  - name: notify
    image: plugins/slack-blame
    settings:
      token:
        from_secret: slack_access_token
      channel: dev
      success_template: |
        The build is fixed! Thanks @{{slack.name}}
      success_image_attachments:
        - 'http://i.imgur.com/TP4PIxc.jpg'
      success_username: successbot
      failure_template: |
        The build is broken! Blame {{slack.name}}
      failure_image_attachments:
        - 'http://m.memegen.com/5wxk2j.jpg'
      failure_username: failurebot

volumes:
  - name: cache
    host:
      path: /var/lib/cache
