kind: pipeline
name: Pipeline

platform:
  os: linux
  arch: amd64

steps:
  - name: install_deps
    image: node:8.15.0
    volumes:
      - name: cache
        path: /tmp/cache
    commands:
      - node -v
      - npm -v
      - yarn -v
      - yarn install --pure-lockfile --cache-folder /tmp/cache/yarn
    when:
      branch:
        - master
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/**']

volumes:
  - name: cache
    host:
      path: /var/lib/cache
