kind: pipeline
name: Default

steps:
  - name: install_dependencies
    image: node:8.15.0
    volumes:
      - name: cache
        path: /tmp/cache
    commands:
      - node -v
      - npm -v
      - yarn -v
      - yarn install --pure-lockfile --cache-folder /tmp/cache/yarn

  - name: app_test
    image: node:8.15.0
    commands:
      - yarn test:app
  - name: app_build
    image: node:8.15.0
    commands:
      - yarn build:app:stage
    when:
      branch: master
      event: push
      status: success
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/app/**']
  - name: app_publish
    image: lucap/drone-netlify
    settings:
      token:
        from_secret: netlify_token
      site_id: 7d8053d6-80e8-4751-9a57-f5b6e8f8c271
      site_name: stage-app-dcabot
      path: packages/app/build
    when:
      branch: master
      event: push
      status: success
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/app/**']

  - name: analytics_publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: registry.amgaventures.com/saas-boilerplate/analytics
      registry: registry.amgaventures.com
      dockerfile: packages/analytics/Dockerfile
      context: packages/analytics
    when:
      branch: master
      event: push
      status: success
      changeset:
        includes: ['yarn.lock', 'package.json', 'packages/analytics/**']

  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_secret
      channel: dev
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded ({{build.link}}). Good job. <@{{build.author}}>
      {{else}}
        build {{build.number}} failed ({{build.link}}). Fix me please. <@channel>
      {{/success}}
    when:
      branch: master
      event: push
      status:
        - success
        - failure

volumes:
  - name: cache
    host:
      path: /var/lib/cache
