apiVersion: v1
kind: Service
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  selector:
    app: analytics
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-deployment
  labels:
    app: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: alfonmga/analytics:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 3000
            initialDelaySeconds: 15
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 2
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: analytics-ingress
spec:
  rules:
    - host: analytics.dcabot.io
      http:
        paths:
          - backend:
              serviceName: analytics
              servicePort: 80
